-- MySQL Script generated by MySQL Workbench
-- 11/18/16 21:09:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poker` DEFAULT CHARACTER SET utf8 ;
USE `poker` ;

-- -----------------------------------------------------
-- Table `poker`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`player` (
  `Name` VARCHAR(25) NOT NULL,
  `Winnings` DECIMAL NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poker`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`table` (
  `TableID` VARCHAR(25) NOT NULL,
  `MaxPlayers` INT NULL,
  `Stakes` VARCHAR(20) NULL,
  `Site` VARCHAR(45) NULL,
  PRIMARY KEY (`TableID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poker`.`hand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`hand` (
  `HandID` BIGINT NOT NULL,
  `TableID` VARCHAR(25) NULL,
  `NumPlayers` INT NULL,
  `StartTime` DATETIME NULL,
  `ButtonPosition` INT NULL,
  `PotSize` DECIMAL NULL,
  `FlopCard1` CHAR(2) NULL,
  `FlopCard2` CHAR(2) NULL,
  `FlopCard3` CHAR(2) NULL,
  `TurnCard` CHAR(2) NULL,
  `RiverCard` CHAR(2) NULL,
  PRIMARY KEY (`HandID`),
  INDEX `TableID_idx` (`TableID` ASC),
  CONSTRAINT `TableID`
    FOREIGN KEY (`TableID`)
    REFERENCES `poker`.`table` (`TableID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poker`.`plays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`plays` (
  `PlayerName` VARCHAR(25) NOT NULL,
  `HandID` BIGINT NOT NULL,
  `StartingStack` DECIMAL NULL,
  `EndingStack` DECIMAL NULL,
  `SeatPosition` INT NULL,
  `HoleCard1` CHAR(2) NULL,
  `HoleCard2` CHAR(2) NULL,
  PRIMARY KEY (`PlayerName`, `HandID`),
  INDEX `HandID_idx` (`HandID` ASC),
  CONSTRAINT `PlayerName`
    FOREIGN KEY (`PlayerName`)
    REFERENCES `poker`.`player` (`Name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `HandID`
    FOREIGN KEY (`HandID`)
    REFERENCES `poker`.`hand` (`HandID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poker`.`hand_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`hand_action` (
  `HandID` BIGINT NOT NULL,
  `ActionID` INT NOT NULL,
  `PlayerName` VARCHAR(25) NULL,
  `ActionName` VARCHAR(45) NULL,
  `Street` VARCHAR(10) NULL,
  `Amount` DECIMAL NULL,
  `IsPFR` BIT NULL,
  `IsVPIP` BIT NULL,
  `Is3Bet` BIT NULL,
  `Is4Bet` BIT NULL,
  PRIMARY KEY (`HandID`, `ActionID`),
  INDEX `PlayerName_idx` (`PlayerName` ASC),
  CONSTRAINT `HandID_Action`
    FOREIGN KEY (`HandID`)
    REFERENCES `poker`.`hand` (`HandID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PlayerName_Action`
    FOREIGN KEY (`PlayerName`)
    REFERENCES `poker`.`player` (`Name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
