-- MySQL Script generated by MySQL Workbench
-- 11/30/16 22:06:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poker` DEFAULT CHARACTER SET utf8 ;
USE `poker` ;
USE `poker` ;

-- -----------------------------------------------------
-- Placeholder table for view `poker`.`player_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`player_stats` (`PlayerName` INT, `HandsPlayed` INT, `Winnings` INT, `VPIP` INT, `PFR` INT, `ThreeBet` INT, `FourBet` INT, `PFAF` INT);

-- -----------------------------------------------------
-- View `poker`.`player_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poker`.`player_stats`;
USE `poker`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `player_stats` AS
    SELECT 
        `ha1`.`PlayerName` AS `PlayerName`,
        COUNT(DISTINCT `ha1`.`HandID`) AS `HandsPlayed`,
        SUM(`ha1`.`Amount`) AS `Winnings`,
        ((SELECT 
                COUNT(DISTINCT `ha2`.`HandID`)
            FROM
                `hand_action` `ha2`
            WHERE
                ((`ha1`.`PlayerName` = `ha2`.`PlayerName`)
                    AND (`ha2`.`Street` = 'Preflop')
                    AND (`ha2`.`ActionName` IN ('RAISE' , 'CALL', 'ALL_IN', 'BET')))) / COUNT(DISTINCT `ha1`.`HandID`)) AS `VPIP`,
        (SUM(`ha1`.`IsPFR`) / COUNT(DISTINCT `ha1`.`HandID`)) AS `PFR`,
        (SUM(`ha1`.`Is3Bet`) / COUNT(DISTINCT `ha1`.`HandID`)) AS `ThreeBet`,
        (SUM(`ha1`.`Is4Bet`) / COUNT(DISTINCT `ha1`.`HandID`)) AS `FourBet`,
        ((SELECT 
                COUNT(0)
            FROM
                `hand_action` `ha3`
            WHERE
                ((`ha3`.`ActionName` IN ('BET' , 'RAISE', 'ALL_IN'))
                    AND (`ha3`.`Street` <> 'Preflop')
                    AND (`ha1`.`PlayerName` = `ha3`.`PlayerName`))) / (SELECT 
                COUNT(0)
            FROM
                `hand_action` `ha4`
            WHERE
                ((`ha1`.`PlayerName` = `ha4`.`PlayerName`)
                    AND (`ha4`.`ActionName` = 'CALL')
                    AND (`ha4`.`Street` <> 'Preflop')))) AS `PFAF`
    FROM
        `hand_action` `ha1`
    GROUP BY `ha1`.`PlayerName`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
