//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hand()
        {
            this.plays = new HashSet<play>();
            this.hand_action = new HashSet<hand_action>();
        }
    
        public long HandID { get; set; }
        public string TableID { get; set; }
        public Nullable<int> NumPlayers { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> ButtonPosition { get; set; }
        public Nullable<decimal> PotSize { get; set; }
        public string FlopCard1 { get; set; }
        public string FlopCard2 { get; set; }
        public string FlopCard3 { get; set; }
        public string TurnCard { get; set; }
        public string RiverCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<play> plays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hand_action> hand_action { get; set; }
        public virtual table table { get; set; }
    }
}
