//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class play
    {
        public long PlayerID { get; set; }
        public long HandID { get; set; }
        public Nullable<decimal> StartingStack { get; set; }
        public Nullable<decimal> EndingStack { get; set; }
        public Nullable<int> SeatPosition { get; set; }
        public string HoleCard1 { get; set; }
        public string HoleCard2 { get; set; }
    
        public virtual hand hand { get; set; }
        public virtual player player { get; set; }
    }
}
