//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_stats
    {
        public long PlayerID { get; set; }
        public string Name { get; set; }
        public long HandsPlayed { get; set; }
        public Nullable<decimal> Winnings { get; set; }
        public Nullable<decimal> VPIP { get; set; }
        public Nullable<decimal> PFR { get; set; }
        public Nullable<decimal> ThreeBet { get; set; }
        public Nullable<decimal> FourBet { get; set; }
        public Nullable<decimal> PFAF { get; set; }
    }
}
