//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_matchups
    {
        public long Player1_ID { get; set; }
        public long Player2_ID { get; set; }
        public string Player1_Name { get; set; }
        public string Player2_Name { get; set; }
        public long HandsPlayed { get; set; }
    }
}
