//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerViewer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokerDB : DbContext
    {
        public PokerDB()
            : base("name=PokerDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hand> hands { get; set; }
        public virtual DbSet<hand_action> hand_action { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<play> plays { get; set; }
        public virtual DbSet<table> tables { get; set; }
        public virtual DbSet<player_stats> player_stats { get; set; }
    }
}
